### ISSUE TITLE
Add stalebot workflow to automatic tests

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4-workflows-common#22]
Extracted from: https://github.com/ckeditor/ckeditor4-workflows-common/pull/15 with [comment](https://github.com/ckeditor/ckeditor4-workflows-common/pull/15#pullrequestreview-642126607).

Currently stalebot has no tests.

Actually, if we prepare a testing repo with `blocked` label and some issues - it should be possible to verify stalebot execution.

**Comment by f1ames** [comment]
That's a little bit different case, since `stalebot` is 3rd-party workflow not one developed by us. Thus if it is already tested there is no need to duplicate the work here.

From what I see it has a [decent tests coverage](https://github.com/actions/stale/tree/main/__tests__). I propose to close this issue then. WDYT @sculpt0r?

**Comment by sculpt0r** [comment]
@f1ames - Indeed.
Don't need to test sth what is already tested. To fast extraction ;) I'm closing it :)
